In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

In [2]:
normal_df = pd.read_csv("Data/NormalMode.csv")
attack1_df = pd.read_csv("Data/Attack1_flood80.csv")
attack2_df = pd.read_csv("Data/Attack2_flood80.csv")
attack3_df = pd.read_csv("Data/Attack3_Ping_and_attack.csv")
attack_df = pd.concat([attack1_df, attack2_df,attack3_df], axis=0)
test_data = pd.read_csv("Data/two consecutive attacks_filter.csv")

normal_df["attack"] = 0
attack_df["attack"] = 1
combined_df = pd.concat([normal_df, attack_df], axis=0)

In [3]:
combined_df.head()

,id,timestamp,device_timestamp,freeheapmemory,networktrafficvolume,packetsize,responsetime,errorrate,powerconsumption,attack
0,20132,2024-08-25 12:02:49.499741+00,14987,48504,0,0,-1,0,0.02,0
1,20133,2024-08-25 12:02:50.730499+00,16196,48064,0,0,-1,0,0.02,0
2,20134,2024-08-25 12:02:51.713495+00,17196,48312,0,0,-1,0,0.02,0
3,20135,2024-08-25 12:02:52.695461+00,18196,48312,0,0,-1,0,0.03,0
4,20136,2024-08-25 12:02:53.714031+00,19196,48312,0,0,-1,0,0.03,0

In [9]:
# Select relevant features for modeling
selected_features = ['responsetime', 'freeheapmemory', 'powerconsumption']

X = combined_df[selected_features]
y = combined_df['attack']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

KeyError: 'attack'

In [7]:
correlation_matrix = train_data.corr()

ValueError: could not convert string to float: '2024-08-25 12:02:49.499741+00'

In [6]:
test_data

,id,timestamp,device_timestamp,freeheapmemory,networktrafficvolume,packetsize,responsetime,errorrate,powerconsumption
0,23041,2024-08-25 16:23:39.001342+00,4918,49992,0,0,-1,0,0.02
1,23042,2024-08-25 16:23:39.755584+00,5918,49280,0,0,0,0,0.05
2,23043,2024-08-25 16:23:40.759613+00,6918,49248,0,0,-1,0,0.05
3,23044,2024-08-25 16:23:42.976688+00,7918,47576,0,0,-1,0,0.07
4,23045,2024-08-25 16:23:44.747102+00,10862,47000,0,0,-1,0,0.02
...,...,...,...,...,...,...,...,...,...
355,23396,2024-08-25 16:32:32.712135+00,538902,47096,0,0,-1,0,0.03
356,23397,2024-08-25 16:32:33.929441+00,539902,47096,0,0,-1,0,0.02
357,23398,2024-08-25 16:32:34.689325+00,540902,47096,0,0,-1,0,0.05
358,23399,2024-08-25 16:32:35.712903+00,541902,47096,0,0,-1,0,0.05
359,23400,2024-08-25 16:32:36.706309+00,542902,47096,0,0,-1,0,0.05